---
abstract: 'Provide the stuff missing in List::Util'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Config::AutoConf: 0.19
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-MoreUtils
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008003
resources:
  repository: https://github.com/perl5-utils/List-MoreUtils
version: 0.400
