---
abstract: 'Provide the stuff missing in List::Util'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.9'
configure_requires:
  Carp: '0'
  Config::AutoConf: '0.19'
  Data::Tumbler: '0.003'
  ExtUtils::MakeMaker: '6.86'
  Module::Pluggable::Object: '5.1'
  Test::WriteVariants: '0.003'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: List-MoreUtils
no_index:
  directory:
    - t
    - inc
recommends:
  perl: '5.018001'
requires:
  Sub::Exporter: '0'
  XSLoader: '0'
  perl: '5.008001'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=List-MoreUtils
  homepage: https://metacpan.org/release/List-MoreUtils
  repository: https://github.com/perl5-utils/List-MoreUtils
version: 0.400_002
